namespace: timhatdiehandandermaus

cronjob:
  name: metadata-updater
  image: ghcr.io/tim-hat-die-hand-an-der-maus/metadata-updater:__TAG__
  imagePullPolicy: IfNotPresent
  schedule: "CRON_TZ=UTC */20 * * * *"
  backoffLimit: 0
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  restartPolicy: Never
  labels:
    app: metadata-updater
  requests:
    cpu: 100m
    memory: 100Mi

configmap:
  name: metadata-updater-config
  imdbResolverUrl: "http://imdb-resolver"
